CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic

strace_0: strace_0.c
	$(CC) $^ -o $@ $(CFLAGS)

strace_1: strace_1.c
	$(CC) $^ -o $@ $(CFLAGS)

strace_2: strace_2.c
	$(CC) $^ -o $@ $(CFLAGS)

strace_3: strace_3.c
	$(CC) $^ -o $@ $(CFLAGS)

PHONY: strace_0 strace_1 strace_2 strace_3
